resources:
- ../../base/istory-app
#- ../../base/istory-db

namespace: istory-prod

patches:
- path: patch-lb-annotations.yml
  target:
    kind: Service
    name: istory-app-lb
- path: patch-deploy.yml
  target:
    kind: Deployment
    name: istory-app-deploy


images:
- name: ekchoi3912/istory
  newName: ekchoi3912/istory
  newTag: "lastest"
    
generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
